 <div class="row-fluid">
  <div class="box span12">
    <div class="box-header well">
      <h2><i class="icon-hdd"></i> Dispositivos</h2>
    </div>
    <div class="box-content">
      <table class="table table-striped table-bordered table-hover bootstrap-datatable datatable">
        <caption></caption>
        <thead>
          <tr>
            <th>Dispositivo</th>
            <th>Nombre</th>
            <th>Marca</th>
            <th>Cantidad</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr>
            <tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr>
            <tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr>
            <tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr>
            <tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr><tr>
              <td>Concentrador</td>
              <td>5bab</td>
              <td>Realtek</td>
              <td>71</td>
            </tr>
            <tr>
              <td>Router</td>
              <td>ee95f2c206</td>
              <td>Tp-Link</td>
              <td>98</td>
            </tr>
        </tbody>
      </table>

     <div class="clearfix"></div>
    </div>
  </div>
</div>